import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Xyrlan - Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased font-semibold selection:bg-none selection:text-lime-600 leading-tight`}>
        <div className="w-full flex items-center flex-col z-[200]">
          <div className="z-10 w-full h-full bg-slate-100 justify-center flex text-zinc-700">
            <div className="flex flex-col px-3 pb-8 w-full border-b border-solid shadow-xl max-w-[1800px] z-[9] text-padding md:px-3 border-neutral-800">
              <Header />
              {children}
            </div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
